# Generated by Django 5.1.1 on 2024-09-11 06:05

from django.db import migrations, models

import users.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("nickname", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(max_length=20)),
                ("phone_number", models.CharField(blank=True, max_length=20, null=True, unique=True)),
                (
                    "social_type",
                    models.CharField(
                        choices=[("common", "Common"), ("kakao", "Kakao"), ("naver", "Naver"), ("google", "Google")],
                        default="common",
                        max_length=20,
                    ),
                ),
                ("email_is_verified", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", users.manager.UserManager()),
            ],
        ),
    ]
