# Generated by Django 5.1.1 on 2024-09-11 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account_number", models.CharField(max_length=16, unique=True)),
                (
                    "bank_code",
                    models.CharField(
                        choices=[
                            ("kakao", "Kakao Bank"),
                            ("kb", "KB Kookmin Bank"),
                            ("nh", "NH NongHyup Bank"),
                            ("ibk", "IBK Industrial Bank of Korea"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings Account"),
                            ("checking", "Checking Account"),
                            ("overdraft", "Overdraft Account"),
                        ],
                        max_length=20,
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
